version: 2

sources:
  - name: destination_db
    description: "Raw data from the destination PostgreSQL database"
    database: destination_db
    schema: public
    tables:
      - name: films
        description: "Table containing films information"
      - name: actors
        description: "Table containing actors information"
      - name: film_actors
        description: "Table linking films and actors that featured in them"